services:
  graphql:
    build:
      dockerfile: Dockerfile
      context: ./graphql-server
    ports:
      - 9002:9002
    image: docker.io/taylorbantle1/dolt-workbench:graphql
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 3000:3000
    image: docker.io/taylorbantle1/dolt-workbench:web
  combined:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
      - 9002:9002
    image: docker.io/taylorbantle1/dolt-workbench:combined
