services:
  graphql:
    build:
      dockerfile: GraphQLDockerfile
      context: .
    command: npm run start
    ports:
      - 9002:9002
  web:
    build:
      dockerfile: WebDockerfile
      context: .
    command: npm run start
    ports:
      - 3002:3000
