services:
  combined:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3000  # Cambiado de 3000:3000 a 3001:3000
      - 9002:9002
    image: docker.io/dolthub/dolt-workbench:latest
